# Use a Node.js base image
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# This is beneficial for caching Docker layers
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Bind the express server to port 3000
EXPOSE 3000

# By default, start the server, but this can be overridden by child images
CMD [ "npm", "start" ]
