name: CI Build, Test, and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Pull the latest docker-framework base image
        run: docker pull registry.example.com/docker-framework/base-image:latest

      - name: Build Docker image
        run: docker build --pull -t registry.example.com/myteam/extended-image:latest .

      - name: Run tests in Docker container
        run: docker run --rm registry.example.com/myteam/extended-image:latest

      - name: Push the Docker image to the registry
        if: success()
        run: docker push registry.example.com/myteam/extended-image:latest

      - name: Notify build and push completion
        if: success()
        run: echo "Docker image has been built and pushed successfully."
